repos:
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
    - id: isort
      args: ["--profile", "black"]
      stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        args:
        - --ignore-missing-imports
        - --disable-error-code=var-annotated

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
        args: ["--fix"]
        stages: [pre-commit]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        args: ["--line-length", "120"]
        stages: [pre-commit]
