# Generated by Django 5.1.4 on 2025-06-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("electricity", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricitymodel",
            name="state",
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
